### ISSUE TITLE
BUG: Entering insert mode 

### ISSUE THREAD

**Issue by julian-raymar** [vscode-neovim/vscode-multi-cursor.nvim#2]
Plugin seems awesome, but I can't quite get it to work. After creating a cursor range with `mcl` I try and enter insert mode with `mci` and get the following error in the vscode-neovim output tab:

```
E5108: Error executing lua: ...de-multi-cursor.nvim/lua/vscode-multi-cursor/cursors.lua:177: attempt to call field 'action' (a nil value)
stack traceback:
	...de-multi-cursor.nvim/lua/vscode-multi-cursor/cursors.lua:177: in function <...de-multi-cursor.nvim/lua/vscode-multi-curso
```

Think the issue is [here](https://github.com/vscode-neovim/vscode-multi-cursor.nvim/blob/77f8f7991f318c58cc1ab461d53496910f947179/lua/vscode-multi-cursor/cursors.lua#L177) - the required vscode-neovim package only has the notify property, it doesn't have action available to it.

**Comment by xiyaowong** [comment]
@julian-raymar Sorry, this plugin needs to wait for vscode-neovim to release version 1.0.0 before it can be used. I've added instructions in the project introduction to avoid others having the same issues
