### ISSUE TITLE
Can action on multiple selected regions?

### ISSUE THREAD

**Issue by defpis** [vscode-neovim/vscode-multi-cursor.nvim#4]
Like vim's visual mode can delete or change selections, if can't, what's the point of entering insert mode after multiple range selection?

**Comment by xiyaowong** [comment]
@defpis Do you mean that you can't press the backspace and modify the content after entering insert mode?

**Comment by xiyaowong** [comment]
As mentioned in the readme, this plugin is only for the convenience of using the vscode multi-selection function. So you need to know what the multi-selection function of vscode can do.

**Comment by defpis** [comment]
I know what insert mode does, but I just don't understand why needs to select the content range after keying mc instead of setting the cursor directly, since subsequent insert operations won't edit the normal mode selected area either. 

For example, I selected different areas via mcs (s is the shortcut key for hop.nvim), and after entering the edit mode, I have no way to change these contents in a uniform way, such as alt+delete can only edit word boundaries, cmd+delete can only edit lines, so what is the meaning of my selection in the first place?

**Comment by xiyaowong** [comment]
The functionality is like this, whether to use it or not, whether it makes sense or not, it completely depends on personal needs... Also, I didn't understand what you meant by setting the cursor directly. Vim doesn't have the concept of multiple cursors.

In addition, I have hardly used them myself...

**Comment by defpis** [comment]
😔
