### ISSUE TITLE
Can't set no_selection=true

### ISSUE THREAD

**Issue by tinoquang** [vscode-neovim/vscode-multi-cursor.nvim#6]
I'm using lazyvim and trying to enable the `no_selection`. Selecting multiple words with `Ctrl + D` then using `mi` creates multi cursor successfully but the words are still selected. My expectation is that I can append to these words after pressing `mi`

![image](https://github.com/vscode-neovim/vscode-multi-cursor.nvim/assets/41105509/96056822-fcf9-497b-bffe-99b5d0ca4a74)

Here's my lua config
```lua
return {
  "vscode-neovim/vscode-multi-cursor.nvim",
  event = "VeryLazy",
  vscode = true,
  opts = function(_, opts)
    vim.keymap.set("n", "<C-d>", "mciw*<Cmd>nohl<CR>", { remap = true })

    local custom_opts = {
      no_selection = true,
    }

    opts = vim.tbl_extend("force", opts, custom_opts)
    return opts
  end,
}
```

**Comment by xiyaowong** [comment]
Please add some print statements to see what the output is.

https://github.com/vscode-neovim/vscode-multi-cursor.nvim/blob/67e101404db09a26acdfccb3a0fdbcc49768b834/lua/vscode-multi-cursor/config.lua#L18-L21

```lua
 function M.setup(opts) 
   config = {} 
   config = M.get(opts) 
   vim.print(config)
 end 
```

**Comment by pdax-maiquang** [comment]
hi @xiyaowong. The config is loaded as expected. Here's the output in vscode 

![image](https://github.com/vscode-neovim/vscode-multi-cursor.nvim/assets/102597526/50647d9d-8c15-483d-abf7-65bc7f9520f1)

**Comment by tinoquang** [comment]
hi @xiyaowong , the config is set correctly. Here's the vscode output

![image](https://github.com/vscode-neovim/vscode-multi-cursor.nvim/assets/102597526/50647d9d-8c15-483d-abf7-65bc7f9520f1)
