### ISSUE TITLE
vscode.get_status_item has been removed

### ISSUE THREAD

**Issue by mrbeardad** [vscode-neovim/vscode-multi-cursor.nvim#8]
Since vscode.get_status_item has been removed, this notify is unnecessary now.

![image](https://github.com/vscode-neovim/vscode-multi-cursor.nvim/assets/54128430/3adb2f63-9bf6-4551-bcac-1734220e0183)

**Comment by xiyaowong** [comment]
![image](https://github.com/vscode-neovim/vscode-multi-cursor.nvim/assets/47070852/cd6942cf-b26e-4a61-a9d7-3969a1b1eed2)
